# Aula 07. Introdução ao ambiente JupyterLab


In [3]:
import numpy as np

<h3>Primeira aula</h3>


In [4]:
b = 0.12
h = 0.4
c = np.sqrt(5**2)
print(c)


5.0


In [5]:
I = b * h**3 / 12
A = b * h

### Funções Trigonométricas


In [6]:
c = np.cos(np.pi / 2)
print(c)
s = np.sin(np.pi / 2)
print(s)

6.123233995736766e-17
1.0


In [7]:
print(np.pi)

3.141592653589793


### Solução de sistemas de equações: $\mathbf{K}\mathbf{x}=\mathbf{F}$, Kx=F


In [8]:
# Declaração de K e F
K = np.array([[5.21, 13.02], [13.02, 41.67]])
F = np.array([553385.41, 1562500])
print(F[1])

1562500.0


In [9]:
# Solução do sistema de equações:
x = np.linalg.solve(K, F)
print(x)

[57078.66563893 19662.4855623 ]


#### Operações matriciais


In [10]:
FF = np.matmul(K, x)
print(FF)
A = np.zeros([4, 2])
print(A)
B = np.ones([3, 6])
print(B)

[ 553385.41 1562500.  ]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Operações condicionais: if-else


In [11]:
# if-else
if h == 0.4:
    print("Altura viga é 40 cm")
else:
    print("Sei lá qual é a altura hehehe")

Altura viga é 40 cm


In [12]:
# il-elseif
h = 0.22
if h == 0.40:
    print("Altura viga é 40 cm")
elif h == 0.30:
    print("Altura da viga é 30 cm")
elif h == 0.20:
    print("Altura da viga é 20 cm")
else:
    print("Sei lá qual é a altura hehehe")

Sei lá qual é a altura hehehe


### Loop utilizando "for


In [13]:
A = np.zeros([2, 2])
print(A)
for i in range(2):
    for j in range(2):
        A[i, j] = F[i] * F[j]

print(A)

[[0. 0.]
 [0. 0.]]
[[3.06235412e+11 8.64664703e+11]
 [8.64664703e+11 2.44140625e+12]]


In [14]:
## Primeira aula

In [21]:
b1, b2, h2, b3 = 0.1, 0.15, 0.4, 0.2

In [23]:
A1 = b1 ** 2
A2 = b2 * h2
A3 = b3 ** 2
I1 = (b1 ** 4) / 12
I2 = (b2 * (h2 ** 3)) / 12
I3 = (b3 ** 4) / 12
E1 = 15 * (10 ** 9)

In [28]:
constants = [[2560, 3 * E1 * I1],
             [4040, 3 * E1 * I2],
             [400, 9 * E1 * A1],
             [-520, 3 * E1 * A3],
             [64, 3 * E1],
             [152, E1 * I2],
             [72, E1 * I3],
             [4, 9 * E1 * A1],
             [6, E1 * A2],
             [2, 3 * E1 * A3]
            ]

Hb = 0
up = 0
down = 0

for i in range(0, len(constants)):
    if i <= 3:
        up = up + constants[i][0] / constants[i][1]
    else:
        down = down + constants[i][0] / constants[i][1]

Hb = up / down
Hb

142.54443562202565